name: teemolab-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unittest:
    name: tests on ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached venv
        id: cached-pyproject-toml
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('./pyproject.toml') }}

      - name: Install dependencies
        if: steps.cached-pyproject-toml.outputs.cache-hit != 'true'
        run: |
          pip install .

      - name: Lint codes
        run: |
          isort --check-only --diff tests/ teemolab/
          pylint tests/ teemolab/
          black --check tests/ teemolab/

      - name: Run tests
        run: pytest tests/
