name: teemolab-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unittest:
    name: tests on ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-22.04"]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: Install dependencies
        run: |
          pip install .
